FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY ./app ${LAMBDA_TASK_ROOT}/

RUN yum install -y python3-devel mysql-devel gcc \
    && yum clean all \
    && pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

CMD ["start_lambda.handler"]